
services:
  app:
    build: .
    container_name: php_app
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/html
      - ./db/sqlite:/var/www/html/db/sqlite/
    depends_on:
      - db
    environment:
      - APACHE_RUN_USER=#1000
      - APACHE_RUN_GROUP=#1000
    restart: unless-stopped

  db:
    image: mysql:8.0
    container_name: mysql_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: phpdb
    volumes:
      - ./db/mysql:/var/lib/mysql
    restart: unless-stopped


